name: Deployment

on:
  merge:
    branches:
    - main

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: VS 2022,  os: windows-2022   }
        - { name: VS 2019,  os: windows-2019   }
        - { name: Linux,    os: ubuntu-latest  }
        - { name: MacOS,    os: macos-latest   }

    steps:
    - uses: actions/checkout@master    

    - name: Install SFML [ Linux ]
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libsfml-dev

    - name: Install SFML [ macOS ]
      if: runner.os == 'macOS'
      run: brew install sfml

    - name: Checkout SFML [ Windows ]
      if: runner.os == 'Windows'
      uses: actions/checkout@master
      with:
        fetch-depth: 0
        repository: SFML/SFML
        ref: 2.6.0
        path: SFML

    - name: Configure SFML [ Windows ]
      if: runner.os == 'Windows'
      shell: bash
      run: cmake -S $GITHUB_WORKSPACE/SFML -B $GITHUB_WORKSPACE/SFML/build -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/SFML/install 
      
    - name: Build SFML [ Windows ]
      if: runner.os == 'Windows'
      shell: bash
      run: cmake --build $GITHUB_WORKSPACE/SFML/build --config Release --target install                           

    - name: Configure CMake for SHARED libraries
      run: cmake -B ${{github.workspace}}/build -DBUILD_SHARED_LIBRARIES=ON -DCMAKE_PREFIX_PATH=${{github.workspace}}/SFML/install/lib/cmake

    - name: Building SHARED libraries
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Publishing STATIC package
      uses: actions/upload-artifact@master
      with:
        name: ${{matrix.platform.name}} SHARED
        path: |
          ${{github.workspace}}/bin
          ${{github.workspace}}/lib
          ${{github.workspace}}/include

    - name: Configure CMake for STATIC libraries
      run: cmake -B ${{github.workspace}}/build -DBUILD_SHARED_LIBRARIES=OFF -DCMAKE_PREFIX_PATH=${{github.workspace}}/SFML/install/lib/cmake

    - name: Building STATIC libraries
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Publishing STATIC package
      uses: actions/upload-artifact@master
      with:
        name: ${{matrix.platform.name}} STATIC
        path: |
          ${{github.workspace}}/bin
          ${{github.workspace}}/lib
          ${{github.workspace}}/include

  Documentation:
    needs: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Generating documentation
      run: |
        sudo apt-get install doxygen &&                                              \
        cd ${{github.workspace}} && doxygen docs/doxyfile.txt                        

    - name: Publishing package
      uses: actions/upload-artifact@master
      with:
        name: Documentation
        path: ${{github.workspace}}/docs/html