name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Installing SFML
      run: sudo apt-get install libsfml-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Building project
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Installing artifacts
      run: cd ${{github.workspace}}/build && make install

    - name: Generating documentation
      run: cd ${{github.workspace}} && sudo apt-get install doxygen && doxygen docs/doxyfile.txt

    - name: Publishing documentation
      uses: actions/upload-artifact@master
      with:
        name: Documentation
        path: ${{github.workspace}}/docs/html