name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install winget
      shell: powershell
      run: |
        # Install NtObjectManager module
        Install-Module NtObjectManager -Force
        # Install winget
        $vclibs = Invoke-WebRequest -Uri "https://store.rg-adguard.net/api/GetFiles" -Method "POST" -ContentType "application/x-www-form-urlencoded" -Body "type=PackageFamilyName&url=Microsoft.VCLibs.140.00_8wekyb3d8bbwe&ring=RP&lang=en-US" -UseBasicParsing | Foreach-Object Links | Where-Object outerHTML -match "Microsoft.VCLibs.140.00_.+_x64__8wekyb3d8bbwe.appx" | Foreach-Object href
        $vclibsuwp = Invoke-WebRequest -Uri "https://store.rg-adguard.net/api/GetFiles" -Method "POST" -ContentType "application/x-www-form-urlencoded" -Body "type=PackageFamilyName&url=Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe&ring=RP&lang=en-US" -UseBasicParsing | Foreach-Object Links | Where-Object outerHTML -match "Microsoft.VCLibs.140.00.UWPDesktop_.+_x64__8wekyb3d8bbwe.appx" | Foreach-Object href
        Invoke-WebRequest $vclibsuwp -OutFile Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe.appx
        Invoke-WebRequest $vclibs -OutFile Microsoft.VCLibs.140.00_8wekyb3d8bbwe.appx
        Add-AppxPackage -Path .\Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe.appx
        Add-AppxPackage -Path .\Microsoft.VCLibs.140.00_8wekyb3d8bbwe.appx
        Invoke-WebRequest https://github.com/microsoft/winget-cli/releases/download/v1.0.11451/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle -OutFile Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle
        Add-AppxPackage -Path .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle
        # Create reparse point
        $installationPath = (Get-AppxPackage Microsoft.DesktopAppInstaller).InstallLocation
        Set-ExecutionAlias -Path "C:\Windows\System32\winget.exe" -PackageName "Microsoft.DesktopAppInstaller_8wekyb3d8bbwe" -EntryPoint "Microsoft.DesktopAppInstaller_8wekyb3d8bbwe!winget" -Target "$installationPath\AppInstallerCLI.exe" -AppType Desktop -Version 3
        explorer.exe "shell:appsFolder\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe!winget"

    - name: Install G/G++
      run: winget install codeblocks
    
    - name: Installing CMake
      run: winget install cmake
    
    - name: Installing SFML for 64 bits
      run: curl https://www.sfml-dev.org/files/SFML-2.5.1-windows-gcc-7.3.0-mingw-64-bit.zip --output "${{github.workspace}}\downloads\SFML-64.zip" && unzip "${{github.workspace}}\downloads\SFML-64.zip"
    
    - name: Preparing build environment
      run: mkdir ${{github.workspace}}\build && cd ${{github.workspace}}\build
    
    - name: Configuring CMake
      run: cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="${{github.workspace}}\downloads\SFML-2.5.1\lib\cmake" ../
      
    - name: Building project
      run: cmake --build . && cmake --install .
      
    - name: Publishing package
      uses: actions/upload-artifact@master
      with:
        name: Windows-64bit
        path: |
          ${{github.workspace}}\bin
          ${{github.workspace}}\lib
          ${{github.workspace}}\include 
          ${{github.workspace}}\example
